### PR TITLE
Restore httpStatusCodetoString

### PR DESCRIPTION
**Pull request by martialblog**
Is still in use. Must have missed it.

### CODE REVIEW

**Comment by martialblog** [comment]
ok ok ok, had ANOTHER look at this. Now I know what's up.

I never saw the `httpStatusCodetoString` function in use, because it is used as `httpStatusCodeToString`:

```php

    public static function httpStatusCodetoString($code = 0)
    {
        $statuscodes = array(
```

```php
            $imageHtml .= $this->translate('Cannot fetch Grafana graph')
                . ": "
                . Util::httpStatusCodeToString($statusCode)
                . " "
```

:facepalm:

**Comment by martialblog** [comment]
Strange, I feel like this must have never worked in the first place? https://github.com/Mikesch-mp/icingaweb2-module-grafana/commit/07afe2131a7f5777a32ebbab40408848874645e9

**Comment by martialblog** [comment]
Today I learned: n PHP, classes, functions and methods are case-insensitive

**Comment by RincewindsHat** [comment]
Say what? Who thought that would be a good idea?

**Pull request merged**
